### ISSUE TITLE
关于重新初始化模型进行预训练

### ISSUE THREAD

**Issue by xiaohuoguohh** [enze5088/Chatterbox#2]
请问后续会有模型初始化以及重新预训练的代码开源吗，从现有的代码看好像是在源模型基础上进行二次预训练

**Comment by nursery42** [comment]
Meta公布的模型没有这个我这个尺寸的，所以并不是从原模型的基础上二次训练。是从一个从0初始化好的模型开始训练。

模型初始化是在其他的代码做的。只要提前填好config.json就可以初始化了。我增加了一个初始化的脚本，你可以参考看一下。重新或者继续预训练用同一套训练代码就可以了。

目前正在训练100GB的base模型，还没训练完成，训练完成后续会同步更新。

**Comment by nursery42** [comment]
https://github.com/enze5088/Chatterbox/tree/main/src/train/model_file/LLaMA-zh-base 这里给出了除模型权重外的参考配置文件。 config.json和tokenizer.json 都是我提前配置或者训练好的。可以直接从这里初始化模型。

**Comment by xiaohuoguohh** [comment]
> Meta公布的模型没有这个我这个尺寸的，所以并不是从原模型的基础上二次训练。是从一个从0初始化好的模型开始训练。
> 
> 模型初始化是在其他的代码做的。只要提前填好config.json就可以初始化了。我增加了一个初始化的脚本，你可以参考看一下。重新或者继续预训练用同一套训练代码就可以了。
> 
> 目前正在训练100GB的base模型，还没训练完成，训练完成后续会同步更新。

了解了！非常感谢～～
