### ISSUE TITLE
block_size和max_position_embeddings

### ISSUE THREAD

**Issue by pfan94** [enze5088/Chatterbox#4]
在`src/train/model_file/LLaMA-zh-base/config.json`中`max_position_embeddings`是2048，也就是说最长输入为2048。但是在`src/train/preprocess.py`里`block_size`默认为512，请问是什么原因呢？

**Comment by nursery42** [comment]
这个单纯是因为训练的时候当时的显卡配置不够，后来升级了机器就给换成512了。不一定要填满的，可以参考自己机器情况而定。
